import type { Campo, Tarea } from './tipos';
import { uid } from './util';

type Base = Omit<Tarea, 'id' | 'activo' | 'galpones'>;

const campo = (c: Partial<Campo> & { etiqueta: string }): Campo => ({
  unidad: '',
  decimales: 0,
  acumulativo: false,
  calculo: 'valor',
  indicador: '',
  ...c,
});

const TODOS = [0, 1, 2, 3, 4, 5, 6];

/** Rutina clásica de un galpón de postura. Es la que se carga al crear la granja. */
export const RUTINA_CLASICA: Base[] = [
  {
    nombre: 'Temperatura mínima y máxima',
    icono: 'termometro',
    tipo: 'numero',
    ayuda: 'Lee el termómetro de mínima y máxima y luego ponlo en cero.',
    campos: [
      campo({ etiqueta: 'Mínima', unidad: '°C', decimales: 1 }),
      campo({ etiqueta: 'Máxima', unidad: '°C', decimales: 1 }),
    ],
    foto: 'obligatoria',
    fotoEtiquetas: ['Termómetro'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Lectura del medidor de agua',
    icono: 'agua',
    tipo: 'numero',
    ayuda: 'Anota el número completo del medidor, siempre a la misma hora.',
    campos: [
      campo({ etiqueta: 'Lectura', unidad: 'L', acumulativo: true, calculo: 'por_ave', indicador: 'ml por ave' }),
    ],
    foto: 'obligatoria',
    fotoEtiquetas: ['Medidor de agua'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Mortalidad',
    icono: 'ave',
    tipo: 'contador',
    ayuda: 'Cuenta las aves muertas retiradas hoy. Si no hay, deja 0.',
    campos: [campo({ etiqueta: 'Aves muertas', unidad: 'aves', calculo: 'pct', indicador: '% del lote' })],
    foto: 'obligatoria',
    fotoEtiquetas: ['Aves retiradas'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Bebederos y niples',
    icono: 'bebedero',
    tipo: 'check',
    ayuda: 'Revisa que haya agua en toda la línea y que no existan fugas.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Comederos y línea de alimento',
    icono: 'comedero',
    tipo: 'check',
    ayuda: 'Revisa que el alimento llegue hasta el final de la línea.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Pediluvio y bioseguridad',
    icono: 'bioseguridad',
    tipo: 'check',
    ayuda: 'Pediluvio con desinfectante, puerta cerrada, sin aves ni animales ajenos.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Huevos recolectados',
    icono: 'huevo',
    tipo: 'numero',
    ayuda: 'Total de huevos del día en este galpón.',
    campos: [campo({ etiqueta: 'Huevos', unidad: 'huevos', calculo: 'pct', indicador: '% de postura' })],
    foto: 'obligatoria',
    fotoEtiquetas: ['Contador o planilla'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Alimento consumido',
    icono: 'alimento',
    tipo: 'numero',
    ayuda: 'Kilos de alimento entregados hoy a este galpón.',
    campos: [campo({ etiqueta: 'Alimento', unidad: 'kg', calculo: 'por_ave', indicador: 'g por ave' })],
    foto: 'opcional',
    fotoEtiquetas: ['Balanza o silo'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Nidos y cintas de huevo',
    icono: 'nido',
    tipo: 'check',
    ayuda: 'Nidos limpios, cintas funcionando, sin huevos acumulados ni rotos.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Pesaje de aves',
    icono: 'balanza',
    tipo: 'fotos',
    ayuda: 'Pesa la muestra de aves, anota en la planilla y toma las dos fotos.',
    campos: [],
    foto: 'obligatoria',
    fotoEtiquetas: ['Pesa con un ave', 'Planilla llena'],
    bloque: 'manana',
    dias: [3],
  },
];

/** Tareas adicionales que el supervisor puede agregar con un toque. */
export const BIBLIOTECA: Base[] = [
  {
    nombre: 'Foto al entrar al galpón',
    icono: 'bioseguridad',
    tipo: 'fotos',
    ayuda: 'Toma una foto de la puerta o del número del galpón al llegar. Queda con hora y ubicación.',
    campos: [],
    foto: 'obligatoria',
    fotoEtiquetas: ['Puerta del galpón'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Huevos sucios o rotos',
    icono: 'huevo',
    tipo: 'contador',
    ayuda: 'Huevos que no pasan a clasificación.',
    campos: [campo({ etiqueta: 'Huevos descartados', unidad: 'huevos', calculo: 'pct', indicador: '% del lote' })],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Cloro en el agua',
    icono: 'cloro',
    tipo: 'numero',
    ayuda: 'Mide el cloro libre en el último bebedero de la línea.',
    campos: [campo({ etiqueta: 'Cloro libre', unidad: 'ppm', decimales: 1 })],
    foto: 'opcional',
    fotoEtiquetas: ['Kit de medición'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Nivel del silo',
    icono: 'alimento',
    tipo: 'numero',
    ayuda: 'Kilos que marca el silo.',
    campos: [campo({ etiqueta: 'Nivel', unidad: 'kg' })],
    foto: 'opcional',
    fotoEtiquetas: ['Silo o visor'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Ventilación y cortinas',
    icono: 'ventilacion',
    tipo: 'check',
    ayuda: 'Ventiladores funcionando y cortinas en la posición indicada.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Iluminación',
    icono: 'luz',
    tipo: 'check',
    ayuda: 'Todas las luces encendidas y el reloj en la hora programada.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Estado de la cama o guano',
    icono: 'cama',
    tipo: 'check',
    ayuda: 'Sin zonas húmedas ni acumulación bajo los bebederos.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Lavado de líneas de agua',
    icono: 'limpieza',
    tipo: 'check',
    ayuda: 'Abre el final de cada línea hasta que salga agua limpia.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: [1],
  },
  {
    nombre: 'Control de roedores',
    icono: 'roedor',
    tipo: 'check',
    ayuda: 'Revisa las estaciones de cebo y repón las que falten.',
    campos: [],
    foto: 'opcional',
    fotoEtiquetas: ['Estación de cebo'],
    bloque: 'tarde',
    dias: [5],
  },
  {
    nombre: 'Retiro de guano',
    icono: 'limpieza',
    tipo: 'check',
    ayuda: 'Cintas de guano funcionando y retiro realizado.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: [2, 5],
  },
];

export const tareaDesde = (b: Base): Tarea => ({
  ...structuredClone(b),
  id: uid(),
  activo: true,
  galpones: null,
});

export const tareaVacia = (): Tarea => ({
  id: uid(),
  nombre: '',
  icono: 'general',
  tipo: 'check',
  ayuda: '',
  campos: [],
  foto: 'no',
  fotoEtiquetas: ['Foto'],
  bloque: 'manana',
  dias: [...TODOS],
  galpones: null,
  activo: true,
});

export const campoVacio = (): Campo => campo({ etiqueta: 'Valor' });

export const CATEGORIAS_PROBLEMA = [
  { id: 'agua', nombre: 'Agua', icono: 'agua' },
  { id: 'alimento', nombre: 'Alimento', icono: 'alimento' },
  { id: 'aves', nombre: 'Aves', icono: 'ave' },
  { id: 'equipo', nombre: 'Equipos', icono: 'equipo' },
  { id: 'instalacion', nombre: 'Galpón', icono: 'galpon' },
  { id: 'otro', nombre: 'Otro', icono: 'general' },
];

export const MOTIVOS_OMITIR = ['No corresponde hoy', 'Equipo en mal estado', 'Faltan insumos', 'No alcancé'];
export const MOTIVOS_CORREGIR = ['Me equivoqué al anotar', 'Leí mal el instrumento', 'Cambió durante el día'];
