import type { Campo, Tarea } from './tipos';
import { uid } from './util';

type Base = Omit<Tarea, 'id' | 'activo' | 'galpones'>;

const campo = (c: Partial<Campo> & { etiqueta: string }): Campo => ({
  unidad: '',
  decimales: 0,
  acumulativo: false,
  calculo: 'valor',
  indicador: '',
  ...c,
});

/** Aves vivas del galpón, que el operario anota cada día después de contar las muertas. */
export const campoAvesVivas = (): Campo => campo({ etiqueta: 'Aves vivas', unidad: 'aves', saldo: true });

const TODOS = [0, 1, 2, 3, 4, 5, 6];

/** Rutina clásica de un galpón de postura. Es la que se carga al crear la granja. */
export const RUTINA_CLASICA: Base[] = [
  {
    nombre: 'Temperatura mínima y máxima',
    icono: 'termometro',
    tipo: 'numero',
    ayuda: 'Lee el termómetro de mínima y máxima y luego ponlo en cero.',
    campos: [
      campo({ etiqueta: 'Mínima', unidad: '°C', decimales: 1 }),
      campo({ etiqueta: 'Máxima', unidad: '°C', decimales: 1 }),
    ],
    foto: 'obligatoria',
    fotoEtiquetas: ['Termómetro'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Lectura del medidor de agua',
    icono: 'agua',
    tipo: 'numero',
    ayuda: 'Anota el número completo del medidor, siempre a la misma hora.',
    campos: [
      campo({ etiqueta: 'Lectura', unidad: 'L', acumulativo: true, calculo: 'por_ave', indicador: 'ml por ave' }),
    ],
    foto: 'obligatoria',
    fotoEtiquetas: ['Medidor de agua'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Mortalidad',
    icono: 'ave',
    tipo: 'contador',
    ayuda: 'Cuenta las aves muertas retiradas hoy. Si no hay, deja 0. Después anota las aves vivas que quedan.',
    campos: [campo({ etiqueta: 'Aves muertas', unidad: 'aves', calculo: 'pct', indicador: '% del lote' }), campoAvesVivas()],
    foto: 'obligatoria',
    fotoEtiquetas: ['Aves retiradas'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Bebederos y niples',
    icono: 'bebedero',
    tipo: 'check',
    ayuda: 'Revisa que haya agua en toda la línea y que no existan fugas.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Comederos y línea de alimento',
    icono: 'comedero',
    tipo: 'check',
    ayuda: 'Revisa que el alimento llegue hasta el final de la línea.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Pediluvio y bioseguridad',
    icono: 'bioseguridad',
    tipo: 'check',
    ayuda: 'Pediluvio con desinfectante, puerta cerrada, sin aves ni animales ajenos.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Huevos recolectados',
    icono: 'huevo',
    tipo: 'numero',
    ayuda: 'Total de huevos del día en este galpón.',
    campos: [campo({ etiqueta: 'Huevos', unidad: 'huevos', calculo: 'pct', indicador: '% de postura' })],
    foto: 'obligatoria',
    fotoEtiquetas: ['Contador o planilla'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Alimento consumido',
    icono: 'alimento',
    tipo: 'numero',
    ayuda: 'Kilos de alimento entregados hoy a este galpón.',
    campos: [campo({ etiqueta: 'Alimento', unidad: 'kg', calculo: 'por_ave', indicador: 'g por ave' })],
    foto: 'opcional',
    fotoEtiquetas: ['Balanza o silo'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Nidos y cintas de huevo',
    icono: 'nido',
    tipo: 'check',
    ayuda: 'Nidos limpios, cintas funcionando, sin huevos acumulados ni rotos.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Pesaje de aves',
    icono: 'balanza',
    tipo: 'fotos',
    ayuda: 'Pesa la muestra de aves, anota en la planilla y toma las dos fotos.',
    campos: [],
    foto: 'obligatoria',
    fotoEtiquetas: ['Pesa con un ave', 'Planilla llena'],
    bloque: 'manana',
    dias: [3],
  },
];

/** Tareas adicionales que el supervisor puede agregar con un toque. */
export const BIBLIOTECA: Base[] = [
  {
    nombre: 'Foto al entrar al galpón',
    icono: 'bioseguridad',
    tipo: 'fotos',
    ayuda: 'Toma una foto de la puerta o del número del galpón al llegar. Queda con hora y ubicación.',
    campos: [],
    foto: 'obligatoria',
    fotoEtiquetas: ['Puerta del galpón'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Huevos sucios o rotos',
    icono: 'huevo',
    tipo: 'contador',
    ayuda: 'Huevos que no pasan a clasificación.',
    campos: [campo({ etiqueta: 'Huevos descartados', unidad: 'huevos', calculo: 'pct', indicador: '% del lote' })],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Cloro en el agua',
    icono: 'cloro',
    tipo: 'numero',
    ayuda: 'Mide el cloro libre en el último bebedero de la línea.',
    campos: [campo({ etiqueta: 'Cloro libre', unidad: 'ppm', decimales: 1, min: 0.2, max: 10 })],
    foto: 'opcional',
    fotoEtiquetas: ['Kit de medición'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Nivel del silo',
    icono: 'alimento',
    tipo: 'numero',
    ayuda: 'Kilos que marca el silo.',
    campos: [campo({ etiqueta: 'Nivel', unidad: 'kg' })],
    foto: 'opcional',
    fotoEtiquetas: ['Silo o visor'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Ventilación y cortinas',
    icono: 'ventilacion',
    tipo: 'check',
    ayuda: 'Ventiladores funcionando y cortinas en la posición indicada.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Iluminación',
    icono: 'luz',
    tipo: 'check',
    ayuda: 'Todas las luces encendidas y el reloj en la hora programada.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Estado de la cama o guano',
    icono: 'cama',
    tipo: 'check',
    ayuda: 'Sin zonas húmedas ni acumulación bajo los bebederos.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Lavado de líneas de agua',
    icono: 'limpieza',
    tipo: 'check',
    ayuda: 'Abre el final de cada línea hasta que salga agua limpia.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: [1],
  },
  {
    nombre: 'Control de roedores',
    icono: 'roedor',
    tipo: 'check',
    ayuda: 'Revisa las estaciones de cebo y repón las que falten.',
    campos: [],
    foto: 'opcional',
    fotoEtiquetas: ['Estación de cebo'],
    bloque: 'tarde',
    dias: [5],
  },
  {
    nombre: 'Retiro de guano',
    icono: 'limpieza',
    tipo: 'check',
    ayuda: 'Cintas de guano funcionando y retiro realizado.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: [2, 5],
  },
  // ---- ambiente
  {
    nombre: 'Humedad del galpón',
    icono: 'termometro',
    tipo: 'numero',
    ayuda: 'Lee el higrómetro a la altura de las aves.',
    campos: [campo({ etiqueta: 'Humedad', unidad: '%', min: 20, max: 95 })],
    foto: 'opcional',
    fotoEtiquetas: ['Higrómetro'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Temperatura de la tarde',
    icono: 'termometro',
    tipo: 'numero',
    ayuda: 'Temperatura a la hora de más calor, a la altura de las aves.',
    campos: [campo({ etiqueta: 'Temperatura', unidad: '°C', decimales: 1 })],
    foto: 'opcional',
    fotoEtiquetas: ['Termómetro'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Olor a amoníaco',
    icono: 'ventilacion',
    tipo: 'check',
    ayuda: 'Al entrar no debe picar en los ojos ni en la nariz.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Horas de luz',
    icono: 'luz',
    tipo: 'numero',
    ayuda: 'Horas de luz que marca el reloj programador.',
    campos: [campo({ etiqueta: 'Horas de luz', unidad: 'h', decimales: 1, min: 8, max: 17 })],
    foto: 'opcional',
    fotoEtiquetas: ['Reloj programador'],
    bloque: 'manana',
    dias: [1],
  },
  // ---- agua
  {
    nombre: 'pH del agua',
    icono: 'cloro',
    tipo: 'numero',
    ayuda: 'Mide el pH en el último bebedero de la línea.',
    campos: [campo({ etiqueta: 'pH', unidad: 'pH', decimales: 1, min: 4, max: 9 })],
    foto: 'opcional',
    fotoEtiquetas: ['Medidor o tira'],
    bloque: 'manana',
    dias: [1],
  },
  {
    nombre: 'Temperatura del agua',
    icono: 'agua',
    tipo: 'numero',
    ayuda: 'Mide el agua al final de la línea de bebederos.',
    campos: [campo({ etiqueta: 'Agua', unidad: '°C', decimales: 1, min: 2, max: 35 })],
    foto: 'no',
    fotoEtiquetas: ['Termómetro'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Altura y presión de bebederos',
    icono: 'bebedero',
    tipo: 'check',
    ayuda: 'Niples a la altura de la cabeza de las aves y gota visible en todos.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Estanque de agua',
    icono: 'agua',
    tipo: 'check',
    ayuda: 'Estanque con agua, tapado y limpio. Flotador funcionando.',
    campos: [],
    foto: 'opcional',
    fotoEtiquetas: ['Estanque'],
    bloque: 'manana',
    dias: [1, 4],
  },
  {
    nombre: 'Medicamento o vitamina en el agua',
    icono: 'cloro',
    tipo: 'fotos',
    ayuda: 'Foto del producto con su etiqueta y de la dosis preparada.',
    campos: [],
    foto: 'obligatoria',
    fotoEtiquetas: ['Etiqueta del producto', 'Dosis preparada'],
    bloque: 'manana',
    dias: TODOS,
  },
  // ---- alimento
  {
    nombre: 'Recepción de alimento',
    icono: 'alimento',
    tipo: 'numero',
    ayuda: 'Kilos recibidos según la guía. Foto de la guía de despacho.',
    campos: [campo({ etiqueta: 'Alimento recibido', unidad: 'kg' })],
    foto: 'obligatoria',
    fotoEtiquetas: ['Guía de despacho'],
    bloque: 'manana',
    dias: [1, 4],
  },
  {
    nombre: 'Calidad del alimento',
    icono: 'comedero',
    tipo: 'check',
    ayuda: 'Sin humedad, hongos, grumos ni olor extraño. Comederos sin alimento viejo.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  // ---- huevos
  {
    nombre: 'Huevos de piso',
    icono: 'huevo',
    tipo: 'contador',
    ayuda: 'Huevos recogidos fuera de los nidos.',
    campos: [campo({ etiqueta: 'Huevos de piso', unidad: 'huevos' })],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Peso del huevo',
    icono: 'balanza',
    tipo: 'numero',
    ayuda: 'Pesa una bandeja de 30 huevos sin la bandeja y anota el promedio por huevo.',
    campos: [campo({ etiqueta: 'Peso promedio', unidad: 'g', decimales: 1, min: 40, max: 80 })],
    foto: 'opcional',
    fotoEtiquetas: ['Balanza'],
    bloque: 'tarde',
    dias: [3],
  },
  {
    nombre: 'Cajas despachadas',
    icono: 'nido',
    tipo: 'numero',
    ayuda: 'Cajas de huevos que salieron hoy del galpón o de la bodega.',
    campos: [campo({ etiqueta: 'Cajas', unidad: 'cajas' })],
    foto: 'opcional',
    fotoEtiquetas: ['Guía o planilla'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Temperatura de la sala de huevos',
    icono: 'termometro',
    tipo: 'numero',
    ayuda: 'Temperatura de la bodega o sala donde se guardan los huevos.',
    campos: [campo({ etiqueta: 'Sala de huevos', unidad: '°C', decimales: 1, min: 0, max: 30 })],
    foto: 'no',
    fotoEtiquetas: ['Termómetro'],
    bloque: 'tarde',
    dias: TODOS,
  },
  // ---- aves
  {
    nombre: 'Peso y uniformidad de las aves',
    icono: 'balanza',
    tipo: 'numero',
    ayuda: 'Pesa la muestra de aves y anota el promedio y la uniformidad de la planilla.',
    campos: [
      campo({ etiqueta: 'Peso promedio', unidad: 'g', min: 800, max: 2600 }),
      campo({ etiqueta: 'Uniformidad', unidad: '%', min: 50, max: 100 }),
    ],
    foto: 'obligatoria',
    fotoEtiquetas: ['Planilla de pesaje'],
    bloque: 'manana',
    dias: [3],
  },
  {
    nombre: 'Comportamiento y plumaje',
    icono: 'ave',
    tipo: 'check',
    ayuda: 'Aves activas y repartidas, sin picaje, sin aves decaídas ni amontonadas.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Fecas',
    icono: 'cama',
    tipo: 'check',
    ayuda: 'Fecas firmes y de color normal, sin sangre ni exceso de agua.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Vacunación o tratamiento',
    icono: 'cloro',
    tipo: 'fotos',
    ayuda: 'Foto del frasco con su etiqueta y lote, y de la planilla firmada.',
    campos: [],
    foto: 'obligatoria',
    fotoEtiquetas: ['Frasco y lote', 'Planilla'],
    bloque: 'manana',
    dias: [1],
  },
  {
    nombre: 'Disposición de aves muertas',
    icono: 'ave',
    tipo: 'check',
    ayuda: 'Aves muertas retiradas del galpón y dejadas en la compostera o el contenedor.',
    campos: [],
    foto: 'opcional',
    fotoEtiquetas: ['Compostera o contenedor'],
    bloque: 'manana',
    dias: TODOS,
  },
  // ---- bioseguridad e instalaciones
  {
    nombre: 'Registro de visitas',
    icono: 'bioseguridad',
    tipo: 'fotos',
    ayuda: 'Foto del libro de visitas del día, si entró alguien ajeno al plantel.',
    campos: [],
    foto: 'obligatoria',
    fotoEtiquetas: ['Libro de visitas'],
    bloque: 'tarde',
    dias: TODOS,
  },
  {
    nombre: 'Cerco y aves silvestres',
    icono: 'galpon',
    tipo: 'check',
    ayuda: 'Mallas y puertas sin roturas. Sin aves silvestres ni otros animales dentro.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: TODOS,
  },
  {
    nombre: 'Control de moscas',
    icono: 'roedor',
    tipo: 'check',
    ayuda: 'Trampas en su lugar y sin acumulación de moscas ni larvas en el guano.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: [2, 5],
  },
  {
    nombre: 'Generador y tablero eléctrico',
    icono: 'equipo',
    tipo: 'check',
    ayuda: 'Generador con combustible y prueba de encendido. Tablero sin alarmas.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: [1],
  },
  {
    nombre: 'Alarmas del galpón',
    icono: 'equipo',
    tipo: 'check',
    ayuda: 'Alarma de temperatura y de corte de luz probadas y funcionando.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'manana',
    dias: [1],
  },
  {
    nombre: 'Limpieza de bebederos y comederos',
    icono: 'limpieza',
    tipo: 'check',
    ayuda: 'Bebederos y comederos sin restos, polvo ni biofilm.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: [6],
  },
  {
    nombre: 'Aseo de pasillos y entrada',
    icono: 'limpieza',
    tipo: 'check',
    ayuda: 'Pasillos barridos, sin alimento derramado, y entrada despejada.',
    campos: [],
    foto: 'no',
    fotoEtiquetas: ['Foto'],
    bloque: 'tarde',
    dias: TODOS,
  },
];

/** Cómo se ordenan las tareas frecuentes al ofrecerlas. Lo que no esté aquí queda en "Otras". */
export const GRUPOS_TAREAS: { titulo: string; nombres: string[] }[] = [
  {
    titulo: 'Aves',
    nombres: ['Mortalidad', 'Comportamiento y plumaje', 'Fecas', 'Pesaje de aves', 'Peso y uniformidad de las aves', 'Vacunación o tratamiento', 'Disposición de aves muertas'],
  },
  {
    titulo: 'Agua',
    nombres: ['Lectura del medidor de agua', 'Bebederos y niples', 'Altura y presión de bebederos', 'Cloro en el agua', 'pH del agua', 'Temperatura del agua', 'Lavado de líneas de agua', 'Estanque de agua', 'Medicamento o vitamina en el agua'],
  },
  {
    titulo: 'Alimento',
    nombres: ['Alimento consumido', 'Comederos y línea de alimento', 'Nivel del silo', 'Recepción de alimento', 'Calidad del alimento'],
  },
  {
    titulo: 'Huevos',
    nombres: ['Huevos recolectados', 'Huevos sucios o rotos', 'Huevos de piso', 'Peso del huevo', 'Nidos y cintas de huevo', 'Cajas despachadas', 'Temperatura de la sala de huevos'],
  },
  {
    titulo: 'Ambiente',
    nombres: ['Temperatura mínima y máxima', 'Temperatura de la tarde', 'Humedad del galpón', 'Olor a amoníaco', 'Ventilación y cortinas', 'Iluminación', 'Horas de luz', 'Estado de la cama o guano', 'Retiro de guano'],
  },
  {
    titulo: 'Bioseguridad e instalaciones',
    nombres: ['Foto al entrar al galpón', 'Pediluvio y bioseguridad', 'Registro de visitas', 'Cerco y aves silvestres', 'Control de roedores', 'Control de moscas', 'Generador y tablero eléctrico', 'Alarmas del galpón', 'Limpieza de bebederos y comederos', 'Aseo de pasillos y entrada'],
  },
];

export const tareaDesde = (b: Base, desde?: string): Tarea => ({
  ...structuredClone(b),
  id: uid(),
  activo: true,
  galpones: null,
  ...(desde ? { desde } : {}),
});

export const tareaVacia = (): Tarea => ({
  id: uid(),
  nombre: '',
  icono: 'general',
  tipo: 'check',
  ayuda: '',
  campos: [],
  foto: 'no',
  fotoEtiquetas: ['Foto'],
  bloque: 'manana',
  dias: [...TODOS],
  galpones: null,
  activo: true,
});

export const campoVacio = (): Campo => campo({ etiqueta: 'Valor' });

export const CATEGORIAS_PROBLEMA = [
  { id: 'agua', nombre: 'Agua', icono: 'agua' },
  { id: 'alimento', nombre: 'Alimento', icono: 'alimento' },
  { id: 'aves', nombre: 'Aves', icono: 'ave' },
  { id: 'equipo', nombre: 'Equipos', icono: 'equipo' },
  { id: 'instalacion', nombre: 'Galpón', icono: 'galpon' },
  { id: 'otro', nombre: 'Otro', icono: 'general' },
];

export const MOTIVOS_OMITIR = ['No corresponde hoy', 'Equipo en mal estado', 'Faltan insumos', 'No alcancé'];
export const MOTIVOS_CORREGIR = ['Me equivoqué al anotar', 'Leí mal el instrumento', 'Cambió durante el día'];
